import { useMemo, useState } from "react";

interface ResponsiveImageProps {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  className?: string;
  sizes?: string; // e.g., "(max-width: 768px) 100vw, 50vw"
  loading?: "lazy" | "eager";
  fetchPriority?: "high" | "low" | "auto";
  decoding?: "async" | "auto" | "sync";
}

/**
 * ResponsiveImage component that uses srcset for optimized image loading
 * 
 * Automatically generates srcset from resized images in /images/resized/
 * Falls back to original image if resized versions don't exist
 */
export const ResponsiveImage = ({
  src,
  alt,
  width,
  height,
  className = "",
  sizes,
  loading = "lazy",
  fetchPriority = "auto",
  decoding = "async",
}: ResponsiveImageProps) => {
  // Extract base name from src (e.g., "/placeholder.webp" -> "placeholder.webp")
  const baseName = useMemo(() => {
    return src.startsWith("/") ? src.slice(1) : src;
  }, [src]);
  
  const baseNameWithoutExt = useMemo(() => {
    return baseName.replace(/\.webp$/, "");
  }, [baseName]);

  // Generate srcset based on common responsive image sizes
  const srcset = useMemo(() => {
    // Determine which sizes are available based on image type
    // This matches the sizes generated by generate-image-sizes.ts
    let availableSizes: number[] = [];
    
    if (width && width <= 100) {
      // Avatars: only include avatar sizes
      availableSizes = [64, 80, 128];
    } else if (width && width <= 700) {
      // Stack images and service images: include relevant sizes
      // Check for specific stack image names (stack2, stack3, stack4, stack5)
      // Not "fullstack" which is a service image
      if (baseNameWithoutExt.match(/^stack[2345]$/)) {
        // Stack images: mobile sizes (362px display) + desktop sizes
        // Added 520w and 550w as intermediate sizes for better coverage
        availableSizes = [362, 400, 520, 550, 600, 634, 951, 1268];
      } else {
        // Service images: mobile sizes + desktop sizes
        // Mobile displays at ~346px, so we need 346w (1x) and 520w (1.5x)
        availableSizes = [346, 520, 606, 909, 1212];
      }
    } else {
      // Large images (placeholder): mobile sizes + desktop sizes
      availableSizes = [400, 600, 668, 1000, 1336];
    }

    const srcsetEntries: string[] = [];

    // Sort sizes to ensure proper ordering (smallest to largest)
    const sortedSizes = [...availableSizes].sort((a, b) => a - b);

    // Generate srcset entries for available sizes
    // The browser will choose the appropriate size based on the sizes attribute
    for (const size of sortedSizes) {
      // Check if this size is relevant based on display width
      if (width && size > width * 2.5) {
        // Skip sizes that are way too large
        continue;
      }

      const resizedPath = `/images/resized/${baseNameWithoutExt}-${size}w.webp`;
      srcsetEntries.push(`${resizedPath} ${size}w`);
    }

    // Always include original as fallback (browsers will use this if srcset images fail)
    // Put original last with a high width descriptor
    srcsetEntries.push(`${src} ${width ? width * 2 : 1920}w`);

    return srcsetEntries.join(", ");
  }, [src, width, baseName, baseNameWithoutExt]);

  // Generate sizes attribute if not provided
  const sizesAttr = useMemo(() => {
    if (sizes) return sizes;
    
    // Default sizes based on display width
    if (width) {
      if (width <= 100) {
        // Small images (avatars)
        return "(max-width: 640px) 64px, 80px";
      } else if (width <= 700) {
        // Medium images (stacks, service images)
        // Check if it's a stack image or service image based on baseNameWithoutExt
        // Use regex to match stack2, stack3, stack4, stack5 specifically (not fullstack)
        if (baseNameWithoutExt.match(/^stack[2345]$/)) {
          // Stack images: displayed at 362px on mobile
          // Be very specific: use exact pixel values that match actual display sizes
          // Account for typical mobile viewports (320-640px) displaying at ~362px
          // On tablet (768px), image is ~400px wide
          // On desktop, be conservative
          return "(max-width: 640px) 362px, (max-width: 768px) 400px, (max-width: 1024px) 450px, (max-width: 1440px) 550px, 634px";
        } else {
          // Service images: displayed at 346px on mobile
          // Be very specific: use exact pixel values that match actual display sizes
          return "(max-width: 640px) 346px, (max-width: 768px) 400px, (max-width: 1024px) 450px, (max-width: 1440px) 550px, 606px";
        }
      } else {
        // Large images (placeholder)
        return "(max-width: 640px) 400px, (max-width: 768px) 100vw, (max-width: 1024px) 90vw, 668px";
      }
    }
    
    // Default fallback
    return "(max-width: 768px) 100vw, 50vw";
  }, [sizes, width, baseName]);

  // Track if we should use original instead of srcset
  const [useOriginal, setUseOriginal] = useState(false);

  // Only use srcset if we have resized images to offer and srcset hasn't failed
  // Otherwise, just use the regular src to avoid browser trying to load non-existent images
  const shouldUseSrcset = !useOriginal && srcset.split(", ").length > 1; // More than just the original

  // Handle error - fall back to original image if using srcset
  const handleError = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
    // If we're using srcset and it fails, fall back to original
    if (shouldUseSrcset) {
      setUseOriginal(true);
      const img = e.currentTarget;
      // Clear srcset and use only src
      img.srcSet = '';
      img.src = src;
    }
  };

  return (
    <img
      src={src}
      srcSet={shouldUseSrcset ? srcset : undefined}
      sizes={shouldUseSrcset ? sizesAttr : undefined}
      alt={alt}
      width={width}
      height={height}
      className={className}
      loading={loading}
      fetchPriority={fetchPriority}
      decoding={decoding}
      onError={handleError}
    />
  );
};

